"use client";import{cacheGet,cachePut,deviceId,metaGet,metaPut,queueAll,queueDelete,queuePut}from"./indexed-db";import type{OfflineMutation,SyncSnapshot}from"./types";import{classifyStatus,retryDelay}from"../../features/offline/state";const listeners=new Set<(s:SyncSnapshot)=>void>();let running=false,snapshot:SyncSnapshot={online:typeof navigator==="undefined"?true:navigator.onLine,phase:"idle",pending:0,retrying:0,conflicts:0,failed:0,lastSyncedAt:null,message:"Up to date"};
export function subscribeSync(fn:(s:SyncSnapshot)=>void){listeners.add(fn);fn(snapshot);return()=>listeners.delete(fn);}function emit(p:Partial<SyncSnapshot>){snapshot={...snapshot,...p};listeners.forEach(x=>x(snapshot));}
export async function enqueueMutation(input:{workspaceId:string;method:OfflineMutation["method"];url:string;headers?:Record<string,string>;body:unknown}){const now=new Date().toISOString(),item:OfflineMutation={id:crypto.randomUUID(),workspaceId:input.workspaceId,deviceId:await deviceId(),method:input.method,url:input.url,headers:{...input.headers,"idempotency-key":input.headers?.["idempotency-key"]??crypto.randomUUID()},body:input.body,createdAt:now,updatedAt:now,attempts:0,nextAttemptAt:null,status:"pending",lastError:null,conflict:null};await queuePut(item);await refresh();if(navigator.onLine)void synchronize();return item;}
export async function synchronize(){if(running||typeof navigator==="undefined")return;running=true;try{if(!navigator.onLine){emit({online:false,phase:"offline",message:"Offline. Changes are saved on this device."});return;}emit({online:true,phase:"syncing",message:"Syncing saved changes..."});const now=Date.now(),items=(await queueAll()).filter(x=>x.status!=="conflict"&&x.status!=="failed"&&(!x.nextAttemptAt||Date.parse(x.nextAttemptAt)<=now)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));for(const item of items)await push(item);await metaPut("lastSyncedAt",new Date().toISOString());await refresh();}finally{running=false;}}
async function push(item:OfflineMutation){item.status="syncing";item.attempts++;item.updatedAt=new Date().toISOString();await queuePut(item);try{const res=await fetch(item.url,{method:item.method,headers:{"content-type":"application/json","x-finance-device-id":item.deviceId,...item.headers},body:JSON.stringify({...asRecord(item.body),deviceId:item.deviceId})});if(res.ok){await queueDelete(item.id);return;}const payload=await res.json().catch(()=>({})),kind=classifyStatus(res.status),message=String(payload.error??("Sync failed with status "+res.status));if(kind==="conflict"){item.status="conflict";item.conflict={status:res.status,message,serverRecord:payload.serverRecord??null,localBody:item.body,detectedAt:new Date().toISOString()};item.nextAttemptAt=null;}else if(kind==="retry"){item.status="retrying";item.nextAttemptAt=new Date(Date.now()+retryDelay(item.attempts)).toISOString();}else item.status="failed";item.lastError=message;await queuePut(item);}catch(e){item.status="retrying";item.lastError=e instanceof Error?e.message:"Network unavailable";item.nextAttemptAt=new Date(Date.now()+retryDelay(item.attempts)).toISOString();await queuePut(item);}}
export async function resolveConflict(id:string,choice:"keep-server"|"retry-local",serverVersion?:number){const item=(await queueAll()).find(x=>x.id===id);if(!item||item.status!=="conflict")return false;if(choice==="keep-server"){await queueDelete(id);await refresh();return true;}item.status="pending";item.conflict=null;item.lastError=null;item.nextAttemptAt=null;if(serverVersion)item.headers["if-match"]=String(serverVersion);item.headers["idempotency-key"]=crypto.randomUUID();await queuePut(item);await synchronize();return true;}
export async function getQueuedMutations(workspaceId?:string){const items=await queueAll();return items.filter(x=>!workspaceId||x.workspaceId===workspaceId).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));}
export async function retryMutation(id:string){const item=(await queueAll()).find(x=>x.id===id);if(!item||item.status==="conflict")return false;item.status="pending";item.lastError=null;item.nextAttemptAt=null;item.updatedAt=new Date().toISOString();await queuePut(item);await refresh();if(navigator.onLine)await synchronize();return true;}
export async function discardMutation(id:string){await queueDelete(id);await refresh();}
export async function cachedJson<T>(workspaceId:string,url:string){const key=workspaceId+":"+url;try{const etag=(await cacheGet<T>(key))?.etag,res=await fetch(url,{headers:etag?{"if-none-match":etag}:{}});if(res.status===304){const c=await cacheGet<T>(key);if(c)return{data:c.value,source:"cache"as const};}if(!res.ok)throw new Error("Request failed");const data=await res.json()as T;await cachePut({key,workspaceId,value:data,etag:res.headers.get("etag"),storedAt:new Date().toISOString()});return{data,source:"network"as const};}catch(e){const c=await cacheGet<T>(key);if(c)return{data:c.value,source:"cache"as const};throw e;}}
async function refresh(){const q=await queueAll(),conflicts=q.filter(x=>x.status==="conflict").length,failed=q.filter(x=>x.status==="failed").length,retrying=q.filter(x=>x.status==="retrying").length,pending=q.length-conflicts-failed;emit({online:navigator.onLine,phase:conflicts?"blocked":navigator.onLine?(pending?"syncing":"idle"):"offline",pending,retrying,conflicts,failed,lastSyncedAt:await metaGet<string>("lastSyncedAt"),message:conflicts?"Review a sync conflict before continuing.":navigator.onLine?(pending?"Changes are waiting to sync.":"Up to date"):"Offline. Changes are saved on this device."});}
export function startAutomaticSync(){if(typeof window==="undefined")return()=>{};const online=()=>void synchronize(),offline=()=>emit({online:false,phase:"offline",message:"Offline. Changes are saved on this device."});window.addEventListener("online",online);window.addEventListener("offline",offline);void refresh();if(navigator.onLine)void synchronize();return()=>{window.removeEventListener("online",online);window.removeEventListener("offline",offline);};}function asRecord(v:unknown){return typeof v==="object"&&v!==null&&!Array.isArray(v)?v as Record<string,unknown>:{};}
