import { toCents,toDecimalString } from "../../domain/money.ts";
const ISO_DATE=/^\d{4}-\d{2}-\d{2}$/;export const TAX_JURISDICTIONS=["federal","state","local","other"]as const;export const RESERVE_DIRECTIONS=["deposit","withdrawal"]as const;
export interface TaxPaymentInput{paymentDate:string;taxYear:number;quarter:1|2|3|4;jurisdiction:(typeof TAX_JURISDICTIONS)[number];amount:string;paymentMethod:string|null;confirmationReference:string|null;notes:string|null;deviceId:string}
export interface ReserveMovementInput{movementDate:string;direction:(typeof RESERVE_DIRECTIONS)[number];amount:string;paymentMethod:string|null;note:string|null;deviceId:string}
export interface TaxVoidInput{reason:string;deviceId:string}
export class TaxInputError extends Error{readonly fields:Record<string,string>;constructor(fields:Record<string,string>){super("Invalid tax record input");this.fields=fields;}}
export function parseTaxPaymentInput(value:unknown):TaxPaymentInput{const s=record(value),f:Record<string,string>={};const taxYear=year(s.taxYear,"taxYear",f),quarter=Number(s.quarter);if(![1,2,3,4].includes(quarter))f.quarter="Select Q1, Q2, Q3, or Q4";const result={paymentDate:date(s.paymentDate,"paymentDate",f),taxYear,quarter:(quarter||1)as 1|2|3|4,jurisdiction:enumValue(s.jurisdiction,TAX_JURISDICTIONS,"jurisdiction",f,"federal"),amount:money(s.amount,"amount",f),paymentMethod:optionalText(s.paymentMethod,80),confirmationReference:optionalText(s.confirmationReference,160),notes:optionalText(s.notes,2000),deviceId:optionalText(s.deviceId,120)??"web"};if(Object.keys(f).length)throw new TaxInputError(f);return result;}
export function parseReserveMovementInput(value:unknown):ReserveMovementInput{const s=record(value),f:Record<string,string>={};const result={movementDate:date(s.movementDate,"movementDate",f),direction:enumValue(s.direction,RESERVE_DIRECTIONS,"direction",f,"deposit"),amount:money(s.amount,"amount",f),paymentMethod:optionalText(s.paymentMethod,80),note:optionalText(s.note,2000),deviceId:optionalText(s.deviceId,120)??"web"};if(Object.keys(f).length)throw new TaxInputError(f);return result;}
export function parseTaxVoidInput(value:unknown):TaxVoidInput{const s=record(value),f:Record<string,string>={};const reason=requiredText(s.reason,"reason",500,f);if(reason&&reason.length<5)f.reason="Explain why this tax record is being removed";if(Object.keys(f).length)throw new TaxInputError(f);return{reason,deviceId:optionalText(s.deviceId,120)??"web"};}
function record(v:unknown):Record<string,unknown>{return typeof v==="object"&&v!==null&&!Array.isArray(v)?v as Record<string,unknown>:{};}function optionalText(v:unknown,m:number){if(typeof v!=="string")return null;const t=v.trim();return t?t.slice(0,m):null;}function requiredText(v:unknown,f:string,m:number,e:Record<string,string>){const t=optionalText(v,m);if(!t)e[f]="This field is required";return t??"";}
function date(v:unknown,f:string,e:Record<string,string>){const t=optionalText(v,10)??"",d=ISO_DATE.test(t)?new Date(`${t}T00:00:00Z`):null;if(!d||Number.isNaN(d.valueOf())||d.toISOString().slice(0,10)!==t)e[f]="Use YYYY-MM-DD";return t;}function year(v:unknown,f:string,e:Record<string,string>){const n=Number(v);if(!Number.isInteger(n)||n<1900||n>2100)e[f]="Enter a year from 1900 through 2100";return n||new Date().getUTCFullYear();}
function money(v:unknown,f:string,e:Record<string,string>){try{const c=toCents(v as string|number|null|undefined);if(c<=0||c>900_000_000_000_000)throw new Error();return toDecimalString(c);}catch{e[f]="Enter an amount greater than zero";return"0.00";}}function enumValue<T extends readonly string[]>(v:unknown,a:T,f:string,e:Record<string,string>,fallback:T[number]):T[number]{if(typeof v==="string"&&a.includes(v))return v as T[number];if(v!==undefined&&v!==null&&v!=="")e[f]="Unsupported value";return fallback;}
