"use client";
import Script from "next/script";
import { useCallback, useEffect, useState } from "react";

type Account = { id: string; account_name: string; account_type: string; mask: string | null; currency: string; current_balance: number | null; available_balance: number | null; balance_updated_at: string | null; is_active: boolean };
type Connection = { id: string; provider: string; institutionName: string; status: "syncing" | "healthy" | "action_required" | "error" | "disconnected"; errorCode: string | null; errorMessage: string | null; lastSyncSucceededAt: string | null; accounts: Account[] };
type PlaidHandler = { open(): void; destroy(): void };
declare global { interface Window { Plaid?: { create(config: { token: string; onSuccess(publicToken: string): void; onExit(error: unknown): void }): PlaidHandler } } }

export default function BankConnections({ workspaceId, workspaceName, canConnect, canSync }: { workspaceId: string; workspaceName: string; canConnect: boolean; canSync: boolean }) {
  const [connections, setConnections] = useState<Connection[]>([]);
  const [scriptReady, setScriptReady] = useState(false);
  const [working, setWorking] = useState<string | null>(null);
  const [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/workspaces/${workspaceId}/bank/connections`); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setConnections(payload.items); }, [workspaceId]);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/workspaces/${workspaceId}/bank/connections`, { signal: controller.signal }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); return payload; }).then((payload) => setConnections(payload.items)).catch((cause) => { if (cause.name !== "AbortError") setError(cause.message); }); return () => controller.abort(); }, [workspaceId]);
  const openPlaid = async (connectionId?: string) => {
    if (!window.Plaid || !scriptReady) { setError("Secure bank linking is still loading. Try again in a moment."); return; }
    setWorking(connectionId ?? "new"); setError("");
    try {
      const tokenResponse = await fetch(`/api/workspaces/${workspaceId}/bank/connections/link-token`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ connectionId }) });
      const token = await tokenResponse.json(); if (!tokenResponse.ok) throw new Error(token.error);
      const handler = window.Plaid.create({ token: token.linkToken, onSuccess: async (publicToken) => { try { if (connectionId) { const sync = await fetch(`/api/workspaces/${workspaceId}/bank/connections/${connectionId}/sync`, { method: "POST" }); if (!sync.ok) throw new Error((await sync.json()).error); } else { const exchange = await fetch(`/api/workspaces/${workspaceId}/bank/connections/exchange`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ publicToken }) }); if (!exchange.ok) throw new Error((await exchange.json()).error); } await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Bank connection failed."); } finally { setWorking(null); handler.destroy(); } }, onExit: () => { setWorking(null); handler.destroy(); } });
      handler.open();
    } catch (cause) { setWorking(null); setError(cause instanceof Error ? cause.message : "Bank connection failed."); }
  };
  const sync = async (id: string) => { setWorking(id); setError(""); try { const response = await fetch(`/api/workspaces/${workspaceId}/bank/connections/${id}/sync`, { method: "POST" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Synchronization failed."); } finally { setWorking(null); } };
  return <div className="mx-auto w-full max-w-[1100px] pb-16"><Script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js" strategy="afterInteractive" onLoad={() => setScriptReady(true)} />
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-700">Bank feed</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-zinc-950 md:text-4xl">Connected banks</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-600">Bring verified bank activity into {workspaceName} without sharing your banking password with Evermont.</p></div>{canConnect && <button disabled={!scriptReady || working !== null} onClick={() => void openPlaid()} className="rounded-full bg-[#143f34] px-6 py-3 text-sm font-semibold text-white shadow-sm disabled:opacity-50">{working === "new" ? "Opening secure connection..." : "Connect a bank"}</button>}</div>
    <div className="mt-7 rounded-2xl border border-emerald-100 bg-emerald-50/70 p-4 text-sm leading-6 text-emerald-950"><strong>How this works.</strong> Plaid handles bank authentication. Finance Studio receives transaction data and read-only account details, then places new activity in your review queue. Nothing is categorized or reconciled without your approval.</div>
    {error && <div role="alert" className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}
    <div className="mt-7 space-y-5">{connections.length ? connections.map((connection) => <section key={connection.id} className="overflow-hidden rounded-3xl border border-zinc-200 bg-white shadow-[0_18px_60px_rgba(20,56,45,0.06)]"><div className="flex flex-col gap-4 border-b border-zinc-200 p-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#143f34] text-lg font-semibold text-white">$</div><div><h2 className="font-semibold text-zinc-950">{connection.institutionName}</h2><p className="mt-1 text-xs text-zinc-500">{connection.lastSyncSucceededAt ? `Updated ${formatDate(connection.lastSyncSucceededAt)}` : "Preparing the first transaction update"}</p></div></div><Health status={connection.status} /></div><div className="divide-y divide-zinc-100">{connection.accounts.map((account) => <div key={account.id} className="flex items-center justify-between gap-5 px-6 py-4"><div className="min-w-0"><p className="truncate text-sm font-semibold text-zinc-900">{account.account_name}</p><p className="mt-1 text-xs capitalize text-zinc-500">{account.account_type.replaceAll("_", " ")} {account.mask ? `•••• ${account.mask}` : ""}</p></div><div className="text-right"><p className="text-sm font-semibold tabular-nums text-zinc-900">{account.current_balance == null ? "Balance unavailable" : money(account.current_balance, account.currency)}</p><p className="mt-1 text-xs text-zinc-500">Current balance</p></div></div>)}</div><div className="flex flex-col gap-3 border-t border-zinc-200 bg-zinc-50 px-6 py-4 sm:flex-row sm:justify-end">{connection.status === "action_required" && canConnect && <button disabled={working !== null} onClick={() => void openPlaid(connection.id)} className="rounded-full border border-amber-300 bg-white px-4 py-2 text-sm font-semibold text-amber-900">Reconnect securely</button>}{canSync && <button disabled={working !== null} onClick={() => void sync(connection.id)} className="rounded-full border border-zinc-300 bg-white px-4 py-2 text-sm font-semibold text-zinc-800">{working === connection.id ? "Synchronizing..." : "Synchronize now"}</button>}</div></section>) : <div className="rounded-3xl border border-dashed border-zinc-300 bg-white p-10 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-50 text-2xl text-emerald-700">$</div><h2 className="mt-5 text-lg font-semibold">No bank is connected</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-500">Connect a business checking, savings, or credit-card account to build your review queue automatically.</p></div>}</div>
  </div>;
}
function Health({ status }: { status: Connection["status"] }) { const styles = status === "healthy" ? "bg-emerald-50 text-emerald-800" : status === "action_required" ? "bg-amber-50 text-amber-800" : status === "error" ? "bg-red-50 text-red-800" : "bg-zinc-100 text-zinc-700"; const label = status === "healthy" ? "Connected" : status === "action_required" ? "Sign-in needed" : status === "error" ? "Needs attention" : "Synchronizing"; return <span className={`self-start rounded-full px-3 py-1.5 text-xs font-semibold ${styles}`}>{label}</span>; }
function money(value: number, currency: string) { return new Intl.NumberFormat("en-US", { style: "currency", currency: currency || "USD" }).format(value); }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)); }
