-- Estimated tax payments and tax-reserve cash movements.
-- Planning records only: this workflow does not calculate or file tax returns.
begin;
alter table public.tax_payments add column if not exists payment_method text,add column if not exists void_reason text,add column if not exists voided_at timestamptz,add column if not exists voided_by uuid references auth.users(id)on delete set null;
alter table public.tax_payments add constraint tax_payments_positive_amount_check check(amount>0);alter table public.tax_payments add constraint tax_payments_year_check check(tax_year between 1900 and 2100);alter table public.tax_payments add constraint tax_payments_jurisdiction_check check(jurisdiction in('federal','state','local','other'));
alter table public.tax_reserve_movements add column if not exists payment_method text,add column if not exists void_reason text,add column if not exists voided_at timestamptz,add column if not exists voided_by uuid references auth.users(id)on delete set null;
alter table public.tax_reserve_movements add constraint tax_reserve_positive_amount_check check(amount>0);
create index tax_payments_workspace_year_date_idx on public.tax_payments(workspace_id,tax_year,payment_date desc)where deleted_at is null;create index tax_reserve_workspace_date_idx on public.tax_reserve_movements(workspace_id,movement_date desc)where deleted_at is null;
create or replace function public.mutate_tax_record(p_workspace_id uuid,p_actor_id uuid,p_client_mutation_id text,p_entity_type text,p_operation text,p_entity_id uuid,p_expected_version bigint,p_payload_hash text,p_record jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_id uuid;v_version bigint;v_before jsonb;v_after jsonb;v_reason text;v_existing_hash text;v_existing_entity text;v_existing_operation text;v_existing_version bigint;v_amount numeric(14,2);
begin
 if p_client_mutation_id is null or length(trim(p_client_mutation_id))<8 then raise exception 'A stable client mutation identifier is required';end if;if p_entity_type not in('tax_payment','tax_reserve_movement')then raise exception 'Unsupported tax record entity';end if;if p_operation not in('create','update','void')then raise exception 'Unsupported tax record operation';end if;
 if not exists(select 1 from public.workspace_members where workspace_id=p_workspace_id and user_id=p_actor_id and role in('owner','admin','member','bookkeeper'))then raise exception 'Not authorized to change tax records';end if;
 select entity_id,entity_type,operation,payload_hash,result_version into v_id,v_existing_entity,v_existing_operation,v_existing_hash,v_existing_version from public.sync_operations where workspace_id=p_workspace_id and client_mutation_id=p_client_mutation_id;
 if v_id is not null then if v_existing_entity<>p_entity_type or v_existing_hash is distinct from nullif(p_payload_hash,'')then raise exception 'Idempotency key was already used for different content';end if;return jsonb_build_object('id',v_id,'operation',v_existing_operation,'version',v_existing_version);end if;
 if p_operation<>'create'and(p_entity_id is null or p_expected_version is null)then raise exception 'Record identifier and expected version are required';end if;if p_operation<>'void'then v_amount:=(p_record->>'amount')::numeric;if v_amount<=0 then raise exception 'Tax record amount must be greater than zero';end if;end if;
 if p_entity_type='tax_payment'then
  if p_operation='create'then insert into public.tax_payments(workspace_id,payment_date,tax_year,quarter,jurisdiction,amount,payment_method,confirmation_reference,notes,created_by)values(p_workspace_id,(p_record->>'paymentDate')::date,(p_record->>'taxYear')::integer,(p_record->>'quarter')::integer,p_record->>'jurisdiction',v_amount,nullif(p_record->>'paymentMethod',''),nullif(p_record->>'confirmationReference',''),nullif(p_record->>'notes',''),p_actor_id)returning id,version into v_id,v_version;
  else select to_jsonb(t.*)into v_before from public.tax_payments t where id=p_entity_id and workspace_id=p_workspace_id and deleted_at is null for update;if v_before is null then raise exception 'Record not found';end if;if(v_before->>'version')::bigint<>p_expected_version then raise exception using errcode='40001',message='Record version conflict';end if;
   if p_operation='update'then update public.tax_payments set payment_date=(p_record->>'paymentDate')::date,tax_year=(p_record->>'taxYear')::integer,quarter=(p_record->>'quarter')::integer,jurisdiction=p_record->>'jurisdiction',amount=v_amount,payment_method=nullif(p_record->>'paymentMethod',''),confirmation_reference=nullif(p_record->>'confirmationReference',''),notes=nullif(p_record->>'notes','')where id=p_entity_id returning id,version into v_id,v_version;
   else v_reason:=nullif(trim(p_record->>'reason'),'');if v_reason is null or length(v_reason)<5 then raise exception 'A void reason is required';end if;update public.tax_payments set void_reason=v_reason,voided_at=now(),voided_by=p_actor_id,deleted_at=now()where id=p_entity_id returning id,version into v_id,v_version;end if;
  end if;select to_jsonb(t.*)into v_after from public.tax_payments t where id=v_id;
 else
  if p_operation='create'then insert into public.tax_reserve_movements(workspace_id,movement_date,direction,amount,payment_method,note,created_by)values(p_workspace_id,(p_record->>'movementDate')::date,p_record->>'direction',v_amount,nullif(p_record->>'paymentMethod',''),nullif(p_record->>'note',''),p_actor_id)returning id,version into v_id,v_version;
  else select to_jsonb(m.*)into v_before from public.tax_reserve_movements m where id=p_entity_id and workspace_id=p_workspace_id and deleted_at is null for update;if v_before is null then raise exception 'Record not found';end if;if(v_before->>'version')::bigint<>p_expected_version then raise exception using errcode='40001',message='Record version conflict';end if;
   if p_operation='update'then update public.tax_reserve_movements set movement_date=(p_record->>'movementDate')::date,direction=p_record->>'direction',amount=v_amount,payment_method=nullif(p_record->>'paymentMethod',''),note=nullif(p_record->>'note','')where id=p_entity_id returning id,version into v_id,v_version;
   else v_reason:=nullif(trim(p_record->>'reason'),'');if v_reason is null or length(v_reason)<5 then raise exception 'A void reason is required';end if;update public.tax_reserve_movements set void_reason=v_reason,voided_at=now(),voided_by=p_actor_id,deleted_at=now()where id=p_entity_id returning id,version into v_id,v_version;end if;
  end if;select to_jsonb(m.*)into v_after from public.tax_reserve_movements m where id=v_id;
 end if;
 insert into public.sync_operations(workspace_id,user_id,device_id,client_mutation_id,entity_type,entity_id,operation,base_version,result_version,payload_hash,status)values(p_workspace_id,p_actor_id,coalesce(nullif(p_record->>'deviceId',''),'web'),p_client_mutation_id,p_entity_type,v_id,p_operation,p_expected_version,v_version,nullif(p_payload_hash,''),'applied');insert into public.audit_events(workspace_id,actor_id,action,entity_type,entity_id,reason,before_data,after_data,request_id)values(p_workspace_id,p_actor_id,p_operation,p_entity_type,v_id,v_reason,v_before,v_after,p_client_mutation_id);return jsonb_build_object('id',v_id,'operation',p_operation,'version',v_version);
end;$$;
revoke all on function public.mutate_tax_record(uuid,uuid,text,text,text,uuid,bigint,text,jsonb)from public,authenticated;grant execute on function public.mutate_tax_record(uuid,uuid,text,text,text,uuid,bigint,text,jsonb)to service_role;
commit;
