-- Durable legacy-backup staging, duplicate keys, and import reconciliation.
begin;
create table public.legacy_import_sessions(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id)on delete cascade,requested_by uuid references auth.users(id)on delete set null,source_sha256 text not null check(source_sha256~'^[0-9a-f]{64}$'),schema_id text not null,schema_revision integer not null default 0,status text not null default'previewed'check(status in('previewed','importing','completed','failed')),source_counts jsonb not null,control_totals jsonb not null,warnings jsonb not null default'[]',report_lines jsonb not null default'[]',created_at timestamptz not null default now(),committed_at timestamptz,unique(workspace_id,source_sha256));
create table public.legacy_import_records(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.legacy_import_sessions(id)on delete cascade,workspace_id uuid not null references public.workspaces(id)on delete cascade,collection text not null,legacy_id text not null,fingerprint text not null check(fingerprint~'^[0-9a-f]{64}$'),payload jsonb not null,status text not null check(status in('ready','duplicate','imported','skipped','error')),target_id uuid,error_message text,created_at timestamptz not null default now(),unique(session_id,collection,legacy_id));
create table public.legacy_import_keys(workspace_id uuid not null references public.workspaces(id)on delete cascade,collection text not null,legacy_id text not null,fingerprint text not null,target_id uuid,imported_at timestamptz not null default now(),primary key(workspace_id,collection,legacy_id),unique(workspace_id,collection,fingerprint));
alter table public.legacy_import_sessions enable row level security;alter table public.legacy_import_records enable row level security;alter table public.legacy_import_keys enable row level security;create policy "members read legacy sessions"on public.legacy_import_sessions for select using(public.is_workspace_member(workspace_id));create policy "members read legacy records"on public.legacy_import_records for select using(public.is_workspace_member(workspace_id));create policy "members read legacy keys"on public.legacy_import_keys for select using(public.is_workspace_member(workspace_id));create index legacy_import_records_session_status_idx on public.legacy_import_records(session_id,status);
create or replace function public.commit_legacy_import(p_workspace_id uuid,p_actor_id uuid,p_session_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$
declare s public.legacy_import_sessions%rowtype;r public.legacy_import_records%rowtype;v_id uuid;v_imported integer:=0;v_skipped integer:=0;v_errors integer:=0;v_amount numeric;v_type text;v_date date;v_cat uuid;v_report jsonb;
begin
 if not exists(select 1 from public.workspace_members where workspace_id=p_workspace_id and user_id=p_actor_id and role in('owner','admin'))then raise exception 'Only workspace owners and administrators can import a legacy backup';end if;
 select * into s from public.legacy_import_sessions where id=p_session_id and workspace_id=p_workspace_id for update;if s.id is null then raise exception 'Import preview not found';end if;if s.status='completed'then return jsonb_build_object('sessionId',s.id,'status',s.status,'report',s.report_lines);end if;if s.status<>'previewed'then raise exception 'This import cannot be committed in its current state';end if;update public.legacy_import_sessions set status='importing'where id=s.id;
 for r in select * from public.legacy_import_records where session_id=s.id and status='ready'order by case collection when'categories'then 1 when'clients'then 2 when'commissions'then 3 when'ledger'then 4 when'trips'then 5 when'subscriptions'then 6 when'taxPayments'then 7 when'reserveMoves'then 8 else 9 end,created_at loop
  begin v_id:=gen_random_uuid();
   if r.collection='categories'then insert into public.categories(id,workspace_id,name,kind,schedule_c_line,is_active,created_by)values(v_id,p_workspace_id,coalesce(nullif(r.payload->>'name',''),'Imported category'),case when coalesce(r.payload->>'kind',r.payload->>'type')='income'then'income'else'expense'end,nullif(coalesce(r.payload->>'scheduleCLine',r.payload->>'schedule_c_line'),''),true,p_actor_id)on conflict(workspace_id,name,kind)do update set schedule_c_line=coalesce(excluded.schedule_c_line,public.categories.schedule_c_line)returning id into v_id;
   elsif r.collection='clients'then insert into public.clients(id,workspace_id,display_name,email,phone,source,notes,created_by)values(v_id,p_workspace_id,coalesce(nullif(coalesce(r.payload->>'displayName',r.payload->>'name',r.payload->>'clientName'),''),'Imported client'),nullif(r.payload->>'email',''),nullif(r.payload->>'phone',''),'legacy_import',nullif(r.payload->>'notes',''),p_actor_id);
   elsif r.collection='commissions'then v_date:=coalesce(nullif(coalesce(r.payload->>'actualPaymentDate',r.payload->>'closedDate',r.payload->>'expectedClosingDate'),'')::date,current_date);insert into public.commissions(id,workspace_id,transaction_reference,side,status,expected_closing_date,closed_date,sales_price,gross_commission,net_received,notes,created_by)values(v_id,p_workspace_id,nullif(r.payload->>'transactionReference',''),case when r.payload->>'side'in('buyer','seller','dual','referral','other')then r.payload->>'side'else'other'end,case when r.payload->>'status'in('lead','under_contract','pending','closed','canceled','void')then r.payload->>'status'else'pending'end,v_date,case when r.payload->>'status'='closed'then v_date else null end,coalesce(nullif(r.payload->>'salesPrice','')::numeric,0),coalesce(nullif(coalesce(r.payload->>'grossCommission',r.payload->>'gross'),'')::numeric,0),coalesce(nullif(coalesce(r.payload->>'netReceived',r.payload->>'net'),'')::numeric,0),nullif(r.payload->>'notes',''),p_actor_id);
   elsif r.collection='ledger'then v_type:=case when r.payload->>'type'in('income','expense','owner_contribution','owner_draw','transfer','refund','reimbursement')then r.payload->>'type'else'expense'end;v_date:=coalesce(nullif(coalesce(r.payload->>'date',r.payload->>'transactionDate'),'')::date,current_date);v_amount:=abs(coalesce(nullif(r.payload->>'amount','')::numeric,0));select target_id into v_cat from public.legacy_import_keys where workspace_id=p_workspace_id and collection='categories'and legacy_id=r.payload->>'categoryId';insert into public.transactions(id,workspace_id,category_id,transaction_date,type,payee,description,amount,payment_method,source,notes,created_by)values(v_id,p_workspace_id,v_cat,v_date,v_type,nullif(r.payload->>'payee',''),coalesce(nullif(r.payload->>'description',''),'Imported legacy record'),v_amount,nullif(r.payload->>'paymentMethod',''),'offline_import',nullif(r.payload->>'notes',''),p_actor_id);
   elsif r.collection='trips'then insert into public.mileage_trips(id,workspace_id,trip_date,purpose,miles,mileage_rate,deduction_amount,parking,tolls,created_by)values(v_id,p_workspace_id,coalesce(nullif(coalesce(r.payload->>'tripDate',r.payload->>'date'),'')::date,current_date),coalesce(nullif(r.payload->>'purpose',''),'Imported business trip'),abs(coalesce(nullif(r.payload->>'miles','')::numeric,0)),coalesce(nullif(coalesce(r.payload->>'mileageRate',r.payload->>'rate'),'')::numeric,0.725),abs(coalesce(nullif(coalesce(r.payload->>'deductionAmount',r.payload->>'deduction'),'')::numeric,0)),abs(coalesce(nullif(r.payload->>'parking','')::numeric,0)),abs(coalesce(nullif(r.payload->>'tolls','')::numeric,0)),p_actor_id);
   elsif r.collection='subscriptions'then v_type:=case when r.payload->>'cadence'in('weekly','monthly','quarterly','semiannual','annual')then r.payload->>'cadence'else'monthly'end;v_amount:=greatest(coalesce(nullif(r.payload->>'amount','')::numeric,0),0.01);insert into public.recurring_expenses(id,workspace_id,vendor_name,product_name,purpose,recurring_type,description,amount,cadence,annualized_amount,next_due_date,auto_pay,reminder_days,is_active,created_by)values(v_id,p_workspace_id,coalesce(nullif(r.payload->>'vendorName',''),'Imported vendor'),nullif(r.payload->>'productName',''),nullif(r.payload->>'purpose',''),'subscription',coalesce(nullif(r.payload->>'description',''),'Imported recurring expense'),v_amount,v_type,round(v_amount*(case v_type when'weekly'then 52 when'monthly'then 12 when'quarterly'then 4 when'semiannual'then 2 else 1 end),2),coalesce(nullif(coalesce(r.payload->>'nextDueDate',r.payload->>'renewalDate'),'')::date,current_date),false,7,true,p_actor_id);
   elsif r.collection='taxPayments'then insert into public.tax_payments(id,workspace_id,payment_date,tax_year,quarter,jurisdiction,amount,notes,created_by)values(v_id,p_workspace_id,coalesce(nullif(coalesce(r.payload->>'paymentDate',r.payload->>'date'),'')::date,current_date),coalesce(nullif(r.payload->>'taxYear','')::integer,extract(year from current_date)::integer),nullif(r.payload->>'quarter','')::integer,case when r.payload->>'jurisdiction'in('federal','state','local','other')then r.payload->>'jurisdiction'else'federal'end,greatest(coalesce(nullif(r.payload->>'amount','')::numeric,0),0.01),nullif(r.payload->>'notes',''),p_actor_id);
   elsif r.collection='reserveMoves'then insert into public.tax_reserve_movements(id,workspace_id,movement_date,direction,amount,note,created_by)values(v_id,p_workspace_id,coalesce(nullif(coalesce(r.payload->>'movementDate',r.payload->>'date'),'')::date,current_date),case when r.payload->>'direction'='withdrawal'then'withdrawal'else'deposit'end,greatest(abs(coalesce(nullif(r.payload->>'amount','')::numeric,0)),0.01),nullif(coalesce(r.payload->>'note',r.payload->>'notes'),''),p_actor_id);
   else update public.legacy_import_records set status='skipped',error_message='This record type is not supported.'where id=r.id;v_skipped:=v_skipped+1;continue;end if;
   insert into public.legacy_import_keys(workspace_id,collection,legacy_id,fingerprint,target_id)values(p_workspace_id,r.collection,r.legacy_id,r.fingerprint,v_id);update public.legacy_import_records set status='imported',target_id=v_id where id=r.id;v_imported:=v_imported+1;
  exception when others then update public.legacy_import_records set status='error',error_message=left(sqlerrm,500)where id=r.id;v_errors:=v_errors+1;end;
 end loop;
 select jsonb_build_array('Finance Studio imported '||v_imported||' records.','It skipped '||v_skipped||' unsupported records and found '||v_errors||' records that need review.','Source control total: $'||(s.control_totals->>'sourceMoney')||'.','Ready-to-import control total: $'||(s.control_totals->>'readyMoney')||'.','Review imported categories, dates, and tax mappings before relying on reports.')into v_report;update public.legacy_import_sessions set status=case when v_errors>0 then'failed'else'completed'end,report_lines=v_report,committed_at=now()where id=s.id;insert into public.audit_events(workspace_id,actor_id,action,entity_type,entity_id,after_data,request_id)values(p_workspace_id,p_actor_id,'import','legacy_backup',s.id,jsonb_build_object('imported',v_imported,'skipped',v_skipped,'errors',v_errors,'sourceSha256',s.source_sha256),'legacy-import:'||s.id);return jsonb_build_object('sessionId',s.id,'status',case when v_errors>0 then'failed'else'completed'end,'imported',v_imported,'skipped',v_skipped,'errors',v_errors,'report',v_report);
end;$$;
revoke all on function public.commit_legacy_import(uuid,uuid,uuid)from public,authenticated;grant execute on function public.commit_legacy_import(uuid,uuid,uuid)to service_role;
commit;
